### ISSUE TITLE
Build fails due to 'annotations' variable not defined / missing 

### ISSUE THREAD

**Issue by darshkpatel** [hallee/eslint-action#10]
So, after our discussion in #3  , I've used the latest version with changes from #6  merged, now there seems to be a new error popping up

```
Error TypeError: Cannot read property 'annotations' of undefined
    at updateCheck (/action/lib/run.js:86:28)
```

https://github.com/frg-fossee/eSim-Cloud/runs/692102494

**Comment by hallee** [comment]
Should be fixed in #13, thanks
